### ISSUE TITLE
this lookbehind (?<=(.|^)) causes "CompileError(LookBehindNotConst)"

### ISSUE THREAD

**Issue by ezw678** [fancy-regex/fancy-regex#109]
this is the complete regex: ".*?(?=XY)(?<=(.|^))XY(?=(.|$))|.+". If I remove |^ or remove .| as follows:

".*?(?=XY)(?<=(.))XY(?=(.|$))|.+"
".*?(?=XY)(?<=(^))XY(?=(.|$))|.+"

it will compile but the result is not correct.

Please take a look. Thanks!

**Comment by keith-hall** [comment]
a similar issue was reported here: https://github.com/fancy-regex/fancy-regex/issues/74

the workaround at the moment is to repeat the pattern up to that point:
`"(?:.*?(?<=.)|(?:.*?(?<=^))(?=XY)XY(?=(.|$))|.+`

but I confess I don't understand your pattern at all, `^|.` will always be true...

**Comment by ezw678** [comment]
good idea. it works;

.*?(?=XY)(?:(?<=(^))|(?<=(.)))XY(?=(.|$))|.+

this is to extract a letter before and after, if existing, a given string, "XY" in this case.
thanks a lot!!!
