### ISSUE TITLE
Is it possible to search backward ?

### ISSUE THREAD

**Issue by kukuro-kt** [fancy-regex/fancy-regex#124]
I tried to use `find_iter(...).rev()` but got error:
```
fn rev(self) -> Rev<Self>
     |        --- required by a bound in this associated function
3397 |     where
3398 |         Self: Sized + DoubleEndedIterator,
     |                       ^^^^^^^^^^^^^^^^^^^ required by this bound in `Iterator::rev`
```

**Comment by robinst** [comment]
That's not possible, no. Looks like not even the regex crate supports that?: https://docs.rs/regex/latest/regex/struct.Matches.html

**Comment by BurntSushi** [comment]
Correct, it does not. It is theoretically possible to do, but an absolute mammoth undertaking.

It is possible, today, to do some amount of reverse searching with the DFA engines. But it's not a nicely supported workflow and you'll be limited to finding matches only. If someone wanted help with that, they could ask a Discussion question on the regex crate repo.
