### ISSUE TITLE
Propagate errors in `replace` instead of using unwrap

### ISSUE THREAD

**Issue by kevinhu** [fancy-regex/fancy-regex#127]
I'm using a couple of lookahead expressions in a text cleaning library I've been working on, and sometimes these run into backtrack limits (`RuntimeError::BacktrackLimitExceeded`). When this happens inside the `replace_all` function, the `.unwrap` call (this [line](https://github.com/fancy-regex/fancy-regex/blob/main/src/lib.rs#L974)) causes a panic that's hard to handle.

Would it be possible to have `replacen` or an alternative return a `Result` that propagates these errors?

**Comment by robinst** [comment]
Yep, that makes sense! Maybe it could be called`try_replacen`? The existing `replacen` would then call that and do an `unwrap()` on it, should be pretty straightforward.

Do you feel comfortable making that change?

**Comment by kevinhu** [comment]
Sure! I've opened a PR here: https://github.com/fancy-regex/fancy-regex/pull/130

**Comment by robinst** [comment]
Thanks! Released in 0.13.0 now: https://github.com/fancy-regex/fancy-regex/blob/0.13.0/CHANGELOG.md#0130---2023-12-22
