### ISSUE TITLE
Recursive Expressions (?R) in Rust's fancy-regex

### ISSUE THREAD

**Issue by shiueo** [fancy-regex/fancy-regex#141]
I've looked through several regex crates in Rust (rust-onig / regex,,). but I haven't seen any that implement recursive expressions `(?R)` (to parse syntax like `{{{((?:[^{}]*|(?R))+)}}}`) yet. The README mentions that this feature is still in development, and while the basic ideas are in place, it states that procedure calls and recursive expressions are currently missing. 

Do you have any updates or timelines regarding when this functionality might be implemented?

**Comment by keith-hall** [comment]
Hi, thanks for your interest. I have the idea that the readme is misleading unfortunately - I don't know of anyone actively working on this feature. And I personally don't think I will have time to work on recursive expressions any time soon. Contributions are very welcome, however 🙂

**Comment by shiueo** [comment]
Thanks for the quick response and clarification!

**Comment by keith-hall** [comment]
FWIW, [I have recently raised a PR with recursion support](https://github.com/fancy-regex/fancy-regex/pull/230), though the syntax is a little different than you asked about - instead of `(?R)` its more like `\g<0>` to recurse the 0th capture group aka whole expression.
