### ISSUE TITLE
Regex should match but doesn't because of delegation

### ISSUE THREAD

**Issue by robinst** [fancy-regex/fancy-regex#37]
The following test case:

```rust
    assert_match(r"((?!x)(?:a|ab))c", "abc");
```

Currently doesn't pass. The reason for this is that `(?:a|ab)` is getting delegated to the regex crate at the moment, which means there's no backtracking. So this happens:

1. Matches `a` from the delegated regex
2. `c` doesn't match
3. There is no backtracking to try `ab` because it's inside the delegated regex

So, it looks like for a group with hard parts, we can't delegate the end unless it's at the end of the pattern. I *think* we can delegate const-size parts, but need to check. But I wonder if there's other situations where we have the same problem. CC @raphlinus

**Comment by intgr** [comment]
Thank you! I was looking forward to this fix.

**Comment by robinst** [comment]
@intgr: Cool. Out of interest, how did you hit this bug?

**Comment by intgr** [comment]
I didn't actually hit the bug. I was impressed by the performance of Rust's regex engine and had a few thoughts where it could be applied. But it didn't support advanced features and the fact that fancy-regex could return incorrect results made me wary.
