### ISSUE TITLE
Add Regex::replace (and replacen, replaceall)

### ISSUE THREAD

**Issue by himat** [fancy-regex/fancy-regex#49]
I thought this crate would have a replace or replace_all like the rust regex crate does.
Is there any way to do replace with this crate?

**Comment by robinst** [comment]
Yeah it doesn't provide replace functionality yet. You can implement it yourself by repeatedly calling `captures_from_pos` and adding the pieces of the string before/after matches.

**Comment by robinst** [comment]
With 0.5.0 you can now use `captures_iter`, which makes it a bit easier. But it would still be nice to have `replace`.

**Comment by intgr** [comment]
I created PR #75 to add replace methods and solve this.

**Comment by robinst** [comment]
Hey! Thanks, I saw them but haven't had a chance to review. Thanks for your patience.

**Comment by robinst** [comment]
Released in 0.7.0, thanks @intgr: https://github.com/fancy-regex/fancy-regex/blob/main/CHANGELOG.md#070---2021-07-12
