### ISSUE TITLE
UnknownFlag("(?<")

### ISSUE THREAD

**Issue by fdncred** [fancy-regex/fancy-regex#50]
Can you please point me in the right direction with this `UnknownFlag` error?

My regex is `(?<color>\[1;34m)(?<word>[[:alnum:][:space:][:punct:]]*).*?(?<other><span|<br)?` and it's stored in a HashMap like this:
```rust
    hash.insert(
        15,
        (
            // Cyan
            r"(?<color>\[36m)(?<word>[[:alnum:][:space:][:punct:]]*).*?(?<other><span|<br)?",
            format!(
                r"<span style='color:{};'>$word</span>",
                color_hm.get("cyan").expect("Error getting cyan text color"),
            ),
        ),
    );
```
I'm looping through the HashMap like this and `Regex::new` is giving this unknownflag on all of regexes.
```rust
    for n in 0..hash_count {
        let value = hash.get(&n).expect("error getting hash at index");
        println!("[{}] [{}]", value.0, value.1);
        let re = Regex::new(&value.0).expect("problem with color regex");
```
I know I must be missing some fundamental item here but I just don't see it. Any help would be greatly appreciated.

**Comment by keith-hall** [comment]
If I'm understanding correctly, the [PR to add named capture group support](https://github.com/fancy-regex/fancy-regex/pull/47) hasn't been merged yet, so that could be the problem.

**Comment by fdncred** [comment]
oh ya, you're right. Duh! I feel so stupid. Wish that change would get in. :) Closing. Thanks @keith-hall !
