### ISSUE TITLE
Q: `case_insensitive` unsupported?

### ISSUE THREAD

**Issue by 4ntoine** [fancy-regex/fancy-regex#66]
Hi, any chance to have `case_insensitive` similar to what is supported in "regex" crate?
```
let new_regex = fancy_regex::RegexBuilder::new(&unescaped_source)
       // .case_insensitive(!self.match_case.clone()) //unsupported by fancy::regex
       .build()
       .unwrap();
```

**Comment by dekellum** [comment]
Is prefixing the regex with "(?i)" a sufficient workaround?

**Comment by 4ntoine** [comment]
@dekellum Thanks, i will try it - just wondered what's the point of having different API (compared to "regex::Regex").

**Comment by robinst** [comment]
Hey, yeah `(?i)` at the start should have the exact same result. It would be nice to add that to the API, in general we want to be as close as possible to regex's API. It's just a matter of doing the work :). I've added a help-wanted label to this.

**Comment by 4ntoine** [comment]
I've found side one related issue: `fancy_regex::Regex::new("??")` is invalid, but `fancy_regex::Regex::new("(?!)??")` is perfectly fine. Seems to be a validation bug.. Can you confirm?

```
    #[test]
    fn test_case() {
        let regex = regex::RegexBuilder::new("??")
            .case_insensitive(true)
            .build();
        assert!(regex.is_err());

        let reg = fancy_regex::Regex::new("(?!)??");
        assert!(reg.is_ok())
    }
```

**Comment by robinst** [comment]
Moved to https://github.com/fancy-regex/fancy-regex/issues/68

Note that the regex crate is expected to fail for `(?!)` because it doesn't support look-ahead. But nevertheless, it's a bug in fancy-regex, look-ahead/behind with repeat operators should not be allowed.

**Comment by 4ntoine** [comment]
I believe this ticket can be closed (and new one "add API" to add options be created if you decide it worth it).
