### ISSUE TITLE
Update owners on crates.io and release new version

### ISSUE THREAD

**Issue by robinst** [fancy-regex/fancy-regex#7]
With the move to a new repo, we should do a release to update the metadata on https://crates.io/crates/fancy-regex

There were also many merged bugfixes. Maybe we should also start writing a CHANGELOG.md file.

@raphlinus Do you mind adding me and the group as a whole as an owner to the crate?:

```
cargo owner --add robinst
cargo owner --add github:fancy-regex:owners
```

(The first command gives me the permissions to extend owners as well, see the docs here: https://doc.rust-lang.org/cargo/reference/publishing.html#cargo-owner)

**Comment by robinst** [comment]
Oh, I found it on crates.io now!

I didn't get an invite because I didn't have an email set on crates.io for some reason.

**Comment by Eh2406** [comment]
I was told to move an issue here if it were still relevant, so I followed the link to find out what it was to decide if it should move, but the olde site had its issues deleted. So I can't tell. All I have to go on is the titles of the emails: witch both seam unresolved: "add a expand to Captures", and "add a captures_iter to Regex".

Also should the old [repo be marked archived](https://blog.github.com/2017-11-08-archiving-repositories/)?

**Comment by raphlinus** [comment]
@Eh2406 Oh, making issues 404 seems pretty drastic, I mostly wanted to make it so new issues wouldn't be filed on the old repo. Archiving does sound like the best solution.

@davelab6 ?

**Comment by cuviper** [comment]
Hi - any update on releasing a new version?

**Comment by robinst** [comment]
Ok, here's a short todo list of things I'd like to do before the release:

* [ ] Change `find` to return a match object, see https://github.com/fancy-regex/fancy-regex/blob/master/src/lib.rs#L202-L204
* [ ] Add some howto style documentation on the module for `is_match` and `find`
* [ ] Add a CHANGELOG.md (see https://keepachangelog.com/en/1.0.0/)

**Comment by robinst** [comment]
Found another thing: Now that we have `Match`, we should also change `Captures` to match regex's API:

* Remove `pos` and `at` methods
* Add `get` method that returns a `Option<Match>`
* Remove `is_empty` (?)

**Comment by TheLostLambda** [comment]
Hiya, how are things going on the new release front? I saw that the Match and Captures note here had a commit. Is there still work to do and can I help out?

**Comment by robinst** [comment]
@TheLostLambda: Thanks for the offer :). I was working on running fancy-regex against the Oniguruma tests, which is now in a PR: #15.

The only thing in there which I'd like to fix before releasing is the panic, the rest can be done later.

**Comment by TheLostLambda** [comment]
@robinst Sounds good! Do you mean that one of the tests causes a panic and you want to fix that? Which test is causing the issue?

**Comment by robinst** [comment]
Yeah, some regexes cause a panic while matching, e.g. this one: https://github.com/fancy-regex/fancy-regex/pull/15/files#diff-2881bc063b93dfc8be4fece6d02954ddR243

**Comment by robinst** [comment]
Done now! 0.2.0 is on crates.io: https://crates.io/crates/fancy-regex

Posted on Reddit as well: https://www.reddit.com/r/rust/comments/djv01f/fancyregex_020_pure_rust_library_for_regexes_with/
