### ISSUE TITLE
Implement Display, Index for feature parity with regex

### ISSUE THREAD

**Issue by duckontheweb** [fancy-regex/fancy-regex#72]
While substituting this crate for `regex` in Stranger6667/jsonschema-rs#220 it came up that there are a couple traits that are implemented on `regex` and not here. These seems like pretty low-hanging fruit and would make it a bit easier to swap this in place of `regex`. These are the ones that I saw, but there may be others:

* [`impl Display for Regex`](https://docs.rs/regex/1.5.4/regex/struct.Regex.html#impl-Display)
* [`impl Index for Captures`](https://docs.rs/regex/1.5.4/regex/struct.Captures.html#impl-Index%3C%26%27i%20str%3E)

I can put in a PR for these 2. I'll take a look at `Clone` and `FromStr` (from #71) as well to see what the level of effort would be there.

**Comment by robinst** [comment]
Released in 0.6.0: https://github.com/fancy-regex/fancy-regex/blob/main/CHANGELOG.md#060---2021-05-17
