### ISSUE TITLE
InvalidClass error

### ISSUE THREAD

**Issue by ronlobo** [fancy-regex/fancy-regex#77]
Hi,

Thanks for putting this together.

I tried the crate for password validation via regex.
The regex can be found [here](https://www.ocpsoft.org/tutorials/regular-expressions/password-regular-expression/) and looks like this:

`^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[*.!@$%^&(){}[]:;<>,.?/~_+-=|\]).{8,32}$`

which, according to the article, can be broken down to:

```
^                                            Match the beginning of the string
(?=.*[0-9])                                  Require that at least one digit appear anywhere in the string
(?=.*[a-z])                                  Require that at least one lowercase letter appear anywhere in the string
(?=.*[A-Z])                                  Require that at least one uppercase letter appear anywhere in the string
(?=.*[*.!@$%^&(){}[]:;<>,.?/~_+-=|\])        Require that at least one special character appear anywhere in the string
.{8,32}                                      The password must be at least 8 characters long, but no more than 32
$                                            Match the end of the string.
```

While testing it, I receive the error "InvalidClass", which appear to be possible in 3 different places.

Are there any known limitations that wouldn't allow this regex?
Would it make sense to add test cases for more convenient use cases?

Thanks.

**Comment by keith-hall** [comment]
> Are there any known limitations that wouldn't allow this regex?

I don't think its about limitations, just fancy-regex is parsing using Oniguruma syntax rules, and that pattern frankly seems a bit dodgy for any parser.

Specifically, the special characters part: `[*.!@$%^&(){}[]:;<>,.?/~_+-=|\]` - the slash before the closing square bracket at the end should probably be escaped, as should the `[]` inside, along with the `-`, the `&` and the `^` as they can have special meaning in character classes.

Don't trust random regular expression patterns you find on the internet - try it somewhere like regex101.com and it may show you/explain all the syntax errors :)

**Comment by ronlobo** [comment]
Thanks @keith-hall, that actually did the trick.
By escaping the suggested characters, it is working as expected.

`^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[*.!@$%\^\&(){}\[\]:;<>,.?\/~_+\-=|\\]).{8,32}$`
